"""empty message

Revision ID: bbb84a39a836
Revises: 21e2e2da54b4
Create Date: 2020-05-25 19:02:12.331746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb84a39a836'
down_revision = '21e2e2da54b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'admin')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
